---
- name: download
  become: yes
  become_user: root
  get_url:
    url: '{{ img_url }}'
    dest: '{{ img_ver_exe }}'
    checksum: '{{ img_checksum }}'
    mode: 0755
- name: link
  become: yes
  become_user: root
  file:
    src: '{{ img_ver_exe }}'
    dest: '{{ img_link }}'
    state: link
